# Generated by Django 5.2.8 on 2025-11-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='criar_tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tarefa', models.CharField(max_length=120)),
                ('descricao_tarefa', models.CharField(default='', max_length=120)),
                ('data_tarefa', models.DateTimeField(verbose_name='Data de Criação')),
            ],
        ),
    ]
