# Generated by Django 5.2.8 on 2025-11-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tarefa', models.CharField(max_length=120)),
                ('descricao_tarefa', models.CharField(default='', max_length=120)),
                ('data_tarefa', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='criar_tarefa',
        ),
    ]
